---
apiVersion: v1
kind: Service
metadata:
  labels:
    cluster.x-k8s.io/provider: bootstrap-kubeadm
    control-plane: controller-manager
  name: capi-kubeadm-bootstrap-controller-manager-metrics-service
  namespace: capi-kubeadm-bootstrap-system
spec:
  ports:
    - name: https
      port: 8443
      targetPort: https
  selector:
    cluster.x-k8s.io/provider: bootstrap-kubeadm
    control-plane: controller-manager
---
apiVersion: v1
kind: Service
metadata:
  labels:
    cluster.x-k8s.io/provider: bootstrap-kubeadm
  name: capi-kubeadm-bootstrap-webhook-service
  namespace: capi-webhook-system
spec:
  ports:
    - port: 443
      targetPort: webhook-server
  selector:
    cluster.x-k8s.io/provider: bootstrap-kubeadm
---
apiVersion: v1
kind: Service
metadata:
  labels:
    cluster.x-k8s.io/provider: control-plane-kubeadm
    control-plane: controller-manager
  name: capi-kubeadm-control-plane-controller-manager-metrics-service
  namespace: capi-kubeadm-control-plane-system
spec:
  ports:
    - name: https
      port: 8443
      targetPort: https
  selector:
    cluster.x-k8s.io/provider: control-plane-kubeadm
    control-plane: controller-manager
---
apiVersion: v1
kind: Service
metadata:
  labels:
    cluster.x-k8s.io/provider: control-plane-kubeadm
  name: capi-kubeadm-control-plane-webhook-service
  namespace: capi-webhook-system
spec:
  ports:
    - port: 443
      targetPort: webhook-server
  selector:
    cluster.x-k8s.io/provider: control-plane-kubeadm
---
apiVersion: v1
kind: Service
metadata:
  labels:
    cluster.x-k8s.io/provider: cluster-api
  name: capi-webhook-service
  namespace: capi-webhook-system
spec:
  ports:
    - port: 443
      targetPort: webhook-server
  selector:
    cluster.x-k8s.io/provider: cluster-api
---
apiVersion: v1
kind: Service
metadata:
  labels:
    cluster.x-k8s.io/provider: cluster-api
    control-plane: controller-manager
  name: capi-controller-manager-metrics-service
  namespace: capi-system
spec:
  ports:
    - name: https
      port: 8443
      targetPort: https
  selector:
    cluster.x-k8s.io/provider: cluster-api
    control-plane: controller-manager
